### PR TITLE
Apply persistence templates to ports in liberty

### PR DESCRIPTION
**Pull request by Cedev**

### CODE REVIEW

**Comment by Cedev** [comment]
Testing on liberty with 4.1.0 acos box:

```
neutron lbaas-loadbalancer-create --name vip1 vipsubnet
neutron lbaas-listener-create --name listener1 --loadbalancer vip1 --protocol HTTP --protocol-port 80
 neutron lbaas-pool-create --name pool1 --lb-algorithm SOURCE_IP --listener listener1 --protocol HTTP --session-persistence type=SOURCE_IP
```

Results in a running config like:

```
ip nat pool a-pool 10.20.30.40 10.20.30.44 netmask /24
!
slb template persist source-ip c3121a3a-0bc9-47c7-bf15-e50a47ccb054
!
slb service-group c3121a3a-0bc9-47c7-bf15-e50a47ccb054 tcp
  method src-ip-hash
!
slb virtual-server e7822d02-1a63-492d-8bc2-11f9a2244735 10.90.101.121
  port 80 http
    name ba48bde3-7f06-49f6-b143-39c97f2fb896
    extended-stats
    source-nat pool a-pool
    service-group c3121a3a-0bc9-47c7-bf15-e50a47ccb054
    template persist source-ip c3121a3a-0bc9-47c7-bf15-e50a47ccb054
!
end
```

**Comment by mdurrant-b3** [comment]
Tests on master and mitaka API versions v21/v30 :+1:

**Comment by mdurrant-b3** [comment]
Successfully tested on liberty 2.7.2 w/ and w/o persistence, tested on liberty 4.1.x w/o persistence.
:+1: shipit.

**Comment by mdurrant-b3** [comment]
:shipit:

**Pull request merged**
