### PR TITLE
"auto" support for v1/v2 drivers + tests

### PR DESCRIPTION
**Pull request by mdurrant-b3**

### CODE REVIEW

**Comment by mdurrant-b3** [comment]
py26 failed miserably on this and ran without issue on my local workstation.

**Comment by mdurrant-b3** [comment]
Adding legacy support to this.

**Comment by mdurrant-b3** [comment]
Fixed PEP issues.  Copy-pasting the Apache license from the first file you find it in disregarding any whitespace is a bad idea FYI.

**Comment by dougwig** [comment]
Good when it can merge. Needs an update.

**Comment by mdurrant-b3** [comment]
Rebased.

**Pull request merged**
