### PR TITLE
Abstract away the device

### PR DESCRIPTION
**Pull request by mdurrant-b3**
Abstract away the device

Completes #187. The handlers don't need to know the details of the device. Abstracting away the details of the device simplifies the handlers, simplifies handling details particular to a device, and makes it easier to add new features that change the way a device works.

This finishes story #147, which was previously completed only for lbaav2. By moving the code that waits for the device to become available from the handler to the device, both lbaasv1 and lbaasv2 handlers wait for newly launched devices to become available.

Also includes story #189, adding nova instance tracking to the services and database models.

----

 * Removes `a10_common.py` and hacking device-version-dependent details into both lbaasv1 and lbaasv2 handlers.
 * Moved responsibility for creating client from context to database appliance model
 * Optional `nova_instance_id` field added to database table, model, extensions, and client.
 * `nova_instance_id` is populated by the instance manager
 * When an appliance stored in the database has a `nova_instance_id`, the additional features for dealing with a nova instance are added to the client.
 * Move responsibility for waiting for nova instance devices to be available from the handler to the device
 * Tests that we can swap out the request method of the device clients to do the waiting

### CODE REVIEW

**Comment by Cedev** [comment]
The `nova_instance_id` needs a `'default': None` in `a10_neutron_lbaas_client/resources/a10_appliance.py`

```
$ neutron a10-appliance-create ax 3.1 admin a10
Failed to parse request. Required attribute 'nova_instance_id' not specified
```

**Comment by Cedev** [comment]
Err, make that `'default': lambda attr: attr.ATTR_NOT_SPECIFIED`, which doesn't give any way to remove it once it's set.

**Comment by Cedev** [comment]
Tested with

 - [x] 2.7.2 device on lbaasv1 by Durrant
 - [x] 4.0.1 device on lbaasv1 by me. It waits, but loadbalancing objects don't get created due to poor performance in double-virtualization
 - [ ] 2.7.2 device on lbaasv2
 - [ ] 4.0.1 device on lbaasv2. Good luck.

**Comment by Cedev** [comment]
Merging despite intractable 2.7.2 and 4.0.1 performance in double-virtualization.

**Comment by mdurrant-b3** [comment]
Reviewed @Cedev's changes :+1:.  Unit tests pass.

**Pull request merged**
