### PR TITLE
initial devstack plugin

### PR DESCRIPTION
**Pull request by dougwig**
- [x] todo - settings vars for config.py info
- [x] todo - auto-enable q-lbaas or q-lbaasv2  (can't do this, but did auto-enable neutron-lbaas plugin, and readme updated

### CODE REVIEW

**Comment by dougwig** [comment]
check

**Comment by dougwig** [comment]
check

**Comment by dougwig** [comment]
check

**Comment by mdurrant-b3** [comment]
lgmt

**Pull request merged**
