### PR TITLE
add option to use member uuid for name

### PR DESCRIPTION
**Pull request by dougwig**

### CODE REVIEW

**Comment by Cedev** [comment]
This looks like it could use a couple quick tests.

**Comment by dougwig** [comment]
check

**Comment by Cedev** [comment]
+1 The automated test failures appear to be test environment issues (missing a device to connect to in one of the 4.0.3 combinations).

```
2016-03-25 23:45:36.347 20454 ERROR neutron_lbaas.services.loadbalancer.plugin   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
2016-03-25 23:45:36.347 20454 ERROR neutron_lbaas.services.loadbalancer.plugin     raise ConnectionError(e, request=request)
2016-03-25 23:45:36.347 20454 ERROR neutron_lbaas.services.loadbalancer.plugin ConnectionError: HTTPSConnectionPool(host='10.48.51.170', port=443): Max retries exceeded with url: /axapi/v3/auth (Caused by 
```

Enough passed to be representative.

**Comment by dougwig** [comment]
check

**Pull request closed without merging**
