### PR TITLE
Alternate shared partition for administrator implemention

### PR DESCRIPTION
**Pull request by mdurrant-b3**
Addresses #72 - not sure I implemented it correctly from a requirements standpoint.  Please review and provide feedback.

### CODE REVIEW

**Comment by dougwig** [comment]
This is good, but I'd simplify it by making the config element just 'shared_partition', with a default of 'shared'.  Then you can just reference it instead of checking if it exists first (the only special case check will be in the actual partition select, where you don't select if 'shared'.)

**Comment by mdurrant-b3** [comment]
Updated code + tests per your comments.

**Comment by 0xtobit** [comment]
It wont let me merge this...

**Comment by mdurrant-b3** [comment]
Rebased.

**Comment by mdurrant-b3** [comment]
Rebased + fixed test.   Wondering about the test in unit config that tests that our array is as long as we think it is.  This has to be updated every time we add a new element to the config for testing purposes (having a regular device versus one setup for alternate partition).

**Comment by Cedev** [comment]
Looks sane to me.

**Pull request merged**
