### PR TITLE
Updated VIP handler HTTPS protocol from TCP to HTTPS

### PR DESCRIPTION
**Pull request by mdurrant-b3**
Fixes protocol type per @actus10 's recommendation.

### CODE REVIEW

**Comment by dougwig** [comment]
Don't merge this. 

Doug

**Comment by mdurrant-b3** [comment]
I never self merge unless it's a CI script or something like that.  Let's chat when you get back.

**Comment by mdurrant-b3** [comment]
We may want to leave this as straight TCP because we want HTTPS traffic not to be mucked with.

**Comment by mdurrant-b3** [comment]
I'm closing this - we want HTTPS to be treated as normal TCP traffic so we don't do any tricky >L4 transformations.

**Pull request closed without merging**
