### PR TITLE
IPINIP support

### PR DESCRIPTION
**Pull request by mdurrant-b3**
Device-specific, config-based IPINIP support for v2. (#88)

### CODE REVIEW

**Comment by dougwig** [comment]
PR needs updating

**Comment by mdurrant-b3** [comment]
Updated.

**Comment by Cedev** [comment]
Needs to be implemented for lbaas v1 as well

**Comment by Cedev** [comment]
I added lbaas v1 support and tests: https://github.com/Cedev/a10-neutron-lbaas/commit/23a5247741d2dd489bf7f0a86df2f6eaf35d7059

**Pull request merged**
