### PR TITLE
Per tenant scaling group binding

### PR DESCRIPTION
**Pull request by Cedev**
Models for a10-openstack's beehive per tenant binding.

For https://github.com/a10networks/a10-openstack-planning/issues/17

---
- scaling group tenant binding table
- a10_scaling_group_tenant_binding_loadbalancers table
- allowed_address_pairs default the mac address when unspecified

Includes testing improvements and fixes for errors discovered by testing improvements
- Tests for migrations, add license to new migrations
- glance client is no longer used in instance manager
- Run tests with mysql
- Create new database for each test
- Fix db column types

### CODE REVIEW

**Comment by mdurrant-b3** [comment]
I'd really like to see tests pass for this...

**Comment by mdurrant-b3** [comment]
I'd like to see tests pass, but LGTM.  I'll merge once tests pass.

**Comment by mdurrant-b3** [comment]
check

**Comment by Cedev** [comment]
check

**Comment by Cedev** [comment]
check

**Comment by Cedev** [comment]
check

**Comment by Cedev** [comment]
check

**Comment by Cedev** [comment]
check

**Comment by mdurrant-b3** [comment]
check

**Comment by mdurrant-b3** [comment]
Closing/reopening to kick the test infrastructure.

**Comment by mdurrant-b3** [comment]
check

**Comment by Cedev** [comment]
This needs fixes for the neutron-lib move that are currently in #382

**Comment by Cedev** [comment]
check

**Comment by Cedev** [comment]
check

**Pull request merged**
